// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

import (
	"github.com/hayashiki/onestep/pkg/model"
)

type CloseProjectResult struct {
	Success bool `json:"success"`
}

type CreateProjectInput struct {
	Name string `json:"name"`
}

type DeleteProjectResult struct {
	Success bool `json:"success"`
}

type ProjectConnection struct {
	Cursor   string           `json:"cursor"`
	HasMore  bool             `json:"hasMore"`
	Projects []*model.Project `json:"projects"`
}

type UpdateProjectInput struct {
	Name string `json:"name"`
}

type UserCreateInput struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type UserUpdateInput struct {
	ID       int     `json:"id"`
	Name     *string `json:"name"`
	Password *string `json:"password"`
	Email    *string `json:"email"`
}
